import React from 'react'
import { Container,Row,Col } from 'react-bootstrap'
import '../../style/about.scss'
import  Parallax from 'react-rellax';

export default function index() {
    return (
        <div style={{marginTop:'15rem'}}>
            <Container >
                <Row className='center-align'>
                
                    <Col sm={12} md={12} xl={5} xxl={5} >
                        <Parallax speed={-2}>
                            <img src={require('../../assets/images/Group 1.png')} alt='who we are' height={400} width='100%'/>
                       

                       
                            <p className="whoweare">who we are</p>
                        </Parallax>
                        
                    </Col>
                    

                    <Col sm={12} md={12} xl={7} xxl={7}>
                        <Parallax speed={-2}>
                             <h6 className='descri_1' > If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.</h6>
                        </Parallax>

                    </Col>
                </Row>

            </Container>



            <Container >

                <Row>

                    <Col sm={12} md={12} xl={7} xxl={7}>
                        <Parallax speed={-2}>
                            <h6 className='descri_1 desc2' > If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.</h6>
                        </Parallax>
                    </Col>

                    <Col sm={12} md={12} xl={5} xxl={5}>
                        <Parallax speed={-2}>
                            <img src={require('../../assets/images/Group 2.png')} alt='who we are' height={400} width='100%'/>
                            <p className="whatwedo" >what we do</p>
                        </Parallax>
                    </Col>

                </Row>

            </Container>



            
        </div>
    )
}
